In [28]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt



In [29]:
#load dataset

sns.load_dataset("tips")


total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
df=sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [32]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [33]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [34]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [35]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [36]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [37]:


#independent and dependent features

df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [38]:
X=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]\

y=df['total_bill']

In [39]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,\
                        random_state=10)

In [40]:
X_train.head()


tip   sex smoker  day    time  size
58   1.76  Male    Yes  Sat  Dinner     2
1    1.66  Male     No  Sun  Dinner     3
2    3.50  Male     No  Sun  Dinner     3
68   2.01  Male     No  Sat  Dinner     2
184  3.00  Male    Yes  Sun  Dinner     2

In [41]:
#feature encoding(label encoding and onhot encoding)

#there will always be problem of data leakage. so first divide
#data and then covnvert

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()


In [44]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

In [24]:
X_train.head(10)

tip  sex  smoker   day  time  size
58   1.76    1       1   Sat     0     2
1    1.66    1       0   Sun     0     3
2    3.50    1       0   Sun     0     3
68   2.01    1       0   Sat     0     2
184  3.00    1       1   Sun     0     2
178  4.00    0       1   Sun     0     2
52   5.20    0       0   Sun     0     4
204  4.00    1       1  Thur     1     4
142  5.00    1       0  Thur     1     5
32   3.00    0       0   Sat     0     2

In [45]:
X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])
X_test['time']=le3.transform(X_test['time'])

In [46]:
X_test.head(10)

tip  sex  smoker   day  time  size
162  2.00    0       0   Sun     0     3
60   3.21    1       1   Sat     0     2
61   2.00    1       1   Sat     0     2
63   3.76    1       1   Sat     0     4
69   2.09    1       1   Sat     0     2
83   5.00    1       1  Thur     1     2
55   3.51    1       0   Sun     0     2
211  5.16    1       1   Sat     0     4
46   5.00    1       0   Sun     0     2
35   3.60    1       0   Sat     0     3

In [48]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


In [61]:
#convert day record in numbers

ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],\
                remainder='passthrough')

#drop=first means 1st column will be dropped and remaining
#columns will be converted

#3rd columne day will be converted and [] means reshaping data
#ow it will show error to reshape data

In [58]:
#

ct.fit_transform(X_train)

array([[1., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 0., 0., 3.],
       [0., 1., 0., ..., 0., 0., 3.],
       ...,
       [1., 0., 0., ..., 0., 0., 2.],
       [0., 0., 1., ..., 0., 1., 6.],
       [0., 1., 0., ..., 0., 0., 2.]])

In [62]:
import sys
import numpy as np

np.set_printoptions(threshold=sys.maxsize)

X_train=ct.fit_transform(X_train)

In [63]:

X_test=ct.fit_transform(X_test)

In [64]:
X_test

array([[0.  , 1.  , 0.  , 2.  , 0.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.76, 1.  , 1.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 2.09, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.6 , 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.65, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.09, 0.  , 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 1.68,

In [66]:
#apply support vector regression

from sklearn.svm import SVR

svr=SVR()

In [67]:
svr.fit(X_train,y_train)

SVR()

In [69]:
y_pred=svr.predict(X_test)
y_pred

array([16.63987262, 17.80422691, 14.49145093, 24.62866424, 14.67173361,
       22.67410166, 19.04664805, 28.29108519, 23.75972181, 21.46546953,
       24.86896212, 17.67206073, 13.44339231, 22.32034304, 19.75694037,
       14.95399101, 13.8566174 , 13.39304164, 21.2171004 , 17.63874958,
       14.32207633, 15.49171819, 14.19580813, 13.3369827 , 29.65235934,
       13.8566174 , 17.37720431, 21.38260597, 14.76962827, 30.02183062,
       28.64203024, 28.03548476, 14.79770992, 15.92806049, 17.56421584,
       13.35938349, 20.52423608, 14.51606288, 20.71506125, 22.18900247,
       16.70814899, 21.52705566, 13.2124233 , 24.44552357, 14.05257741,
       14.13643952, 18.52010744, 14.79770992, 13.74271464, 18.54833482,
       20.82086506, 29.78470039, 19.41806679, 27.8646883 , 13.01786739,
       16.91813134, 14.06890087, 14.15277698, 17.87180292, 13.83656792,
       17.37317545])

In [70]:
from sklearn.metrics import r2_score,mean_absolute_error

print(r2_score(y_test,y_pred))

print(mean_absolute_error(y_test,y_pred))

0.46028114561159283
4.1486423210190235


In [73]:
#Hyper Parameter turning using GridSearch CV

from sklearn.model_selection import GridSearchCV

In [75]:
param_grid={'C':[0.1,1,10,100,1000],
            'gamma':[1,0.1,0.01,0.001,0.0001],
            'kernel':['rbf']}

In [77]:
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3)

grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.067 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.058 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.145 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.025 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.089 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.013 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.021 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.010 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.124 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.050 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.053 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=rbf;

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [78]:
grid.best_params_

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}

In [79]:
grid_pred=grid.predict(X_test)


In [80]:
from sklearn.metrics import r2_score,mean_absolute_error

print(r2_score(y_test,grid_pred))

print(mean_absolute_error(y_test,grid_pred))

0.5081618245078687
3.8685147526100234
