In [5]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

from sklearn.metrics import classification_report,\
accuracy_score,confusion_matrix


In [6]:
#import dataset

X,y= make_classification(
    n_samples=1000,
    n_features=3,
    n_redundant=1,
    n_classes=2,
    random_state=999
)

In [7]:
#train data set

X_train,X_test,y_train,y_test=train_test_split(X,y,
                    test_size=0.33,random_state=42)



In [9]:
X_train

array([[-1.06405731, -0.22324023,  1.09027381],
       [-1.0061151 , -0.22717707,  0.89758841],
       [-1.23920161, -0.39578173,  0.14480054],
       ...,
       [-0.62173685, -0.12586518,  0.67496125],
       [ 1.63275027,  0.7152537 ,  1.41447324],
       [ 0.21192241, -0.11262328, -1.51843229]])

In [10]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,

In [17]:
#build a model

classifier=KNeighborsClassifier(n_neighbors=5,algorithm="auto")
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [18]:
#predict

y_pred=classifier.predict(X_test)
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,

In [19]:
#metrics

print(accuracy_score(y_pred,y_test))

print(confusion_matrix(y_pred,y_test))

print(classification_report(y_pred,y_test))

0.906060606060606
[[158  20]
 [ 11 141]]
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       178
           1       0.88      0.93      0.90       152

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [26]:
#hyper parameter tuning

from sklearn.model_selection import GridSearchCV

param_grid = {"n_neighbors": [k for k in range(1,100)],\
           "weights":["uniform","distance"],\
            "algorithm":["auto", "ball_tree", "kd_tree", "brute"],
              'metric' : ['minkowski','euclidean','manhattan']}

In [28]:
grid=GridSearchCV(KNeighborsClassifier(),param_grid=param_grid,cv=5,refit=True,verbose=3)
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30, ...],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [31]:
grid.fit(X_train,y_train)

Streaming output truncated to the last 5000 lines.
[CV 1/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=uniform;, score=0.903 total time=   0.0s
[CV 2/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=uniform;, score=0.888 total time=   0.0s
[CV 3/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=uniform;, score=0.836 total time=   0.0s
[CV 4/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=uniform;, score=0.881 total time=   0.0s
[CV 5/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=uniform;, score=0.858 total time=   0.0s
[CV 1/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=distance;, score=0.910 total time=   0.0s
[CV 2/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=distance;, score=0.903 total time=   0.0s
[CV 3/5] END algorithm=kd_tree, metric=minkowski, n_neighbors=95, weights=distance;, score=0.866 total time=   0.0s
[CV 4/5] END algorithm=kd_

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29, 30, ...],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [32]:
grid.best_params_

{'algorithm': 'auto',
 'metric': 'minkowski',
 'n_neighbors': 9,
 'weights': 'uniform'}

In [33]:
grid.best_score_

0.9029850746268657

In [34]:

y_pred=grid.predict(X_test)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.92      0.91       169
           1       0.92      0.90      0.91       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330

[[156  13]
 [ 16 145]]
